#!/bin/sh

set -e

sqlite3_options="-C -DSQLITE_ENABLE_FTS3 -C -DSQLITE_ENABLE_FTS3_PARENTHESIS -C -DSQLITE_THREADSAFE=0"

if ./use-system-sqlite3; then
    echo "SQlite3 version `./version-check` found"
    "$CHICKEN_CSC" -C "$CFLAGS -DUSE_SYSTEM_SQLITE=1" -L "$LDFLAGS -lsqlite3" -Isqlite3 "$@"
else
    echo "Using built-in SQLite3"
    "$CHICKEN_CSC" -C "$CFLAGS" -L "$LDFLAGS" \
		   -Isqlite3 "$@" sqlite3/sqlite3.c \
		   $sqlite3_options -C -DSQLITE_THREADSAFE=0
fi
