#!/bin/sh

set -e

sqlite3_options="-C -DSQLITE_ENABLE_FTS3 -C -DSQLITE_ENABLE_FTS3_PARENTHESIS -C -DSQLITE_THREADSAFE=0"

if /bin/sh ./use-system-sqlite3; then
    echo "SQlite3 version `./version-check` found"
    cp chicken-sqlite3.sh chicken-sqlite3
else
    echo "Using built-in SQLite3"
    "$CHICKEN_CSC" -C "$CFLAGS" -L "$LDFLAGS" \
		   -Isqlite3 "$@" sqlite3/sqlite3.c \
		   $sqlite3_options -C -DSQLITE_THREADSAFE=0
fi
