name: chicken cache
on:
  workflow_dispatch:
  push:
  pull_request:
env:
    CHICKEN_VERSION: 5.3.0

jobs:
  chicken:
    name: Chicken cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "CHICKEN_PREFIX=$HOME/local/chicken-$CHICKEN_VERSION" >> $GITHUB_ENV

      - name: Cache Chicken compiler
        id: cache-chicken
        uses: actions/cache@v3
        with:
          path: ${{ env.CHICKEN_PREFIX }}
          key: chicken-${{ env.CHICKEN_VERSION }}

      - name: Build Chicken
        run: |
          SRC=$HOME/src
          mkdir -p $SRC
          wget -O - https://code.call-cc.org/releases/$CHICKEN_VERSION/chicken.tar.gz | tar -zxC $SRC
          cd $SRC/chicken-$CHICKEN_VERSION
          make PLATFORM=linux PREFIX=$CHICKEN_PREFIX install
        if: steps.cache-chicken.outputs.cache-hit != 'true'

      - name: Display Chicken version
        run: $CHICKEN_PREFIX/bin/csi -version

      - name: Get hash of egg dependencies
        id: deps
        run: |
            deps=$($CHICKEN_PREFIX/bin/csi -e "(print (assoc 'dependencies (read)))" < *.egg)
            echo "deps=$deps" >> $GITHUB_OUTPUT
            echo "deps_hash=$(echo $deps | md5sum)" >> $GITHUB_OUTPUT

      - name: Cache Chicken eggs
        id: cache-eggs
        uses: actions/cache@v3
        with:
          path: ~/.cache/chicken-install
          # Note: Hashing the entire .egg file is overzealous. Instead, hash just the
          # dependencies.
          key: chicken-eggs-${{ env.CHICKEN_VERSION }}-${{ steps.deps.outputs.deps_hash }}

      - name: Install and test egg
        run: |
            $CHICKEN_PREFIX/bin/chicken-install -test

      # Note: Installing the egg will also cache it for later. That will be unconditionally 
      # overwritten on next install, but it might be a good idea to remove it.
